# ?????? ???????????
logging.level.org.zalando.logbook=TRACE
logging.level.ru.yandex.practicum.filmorate=DEBUG

# ?????????????? ????????? Logbook
logbook.include.request.body=true
logbook.include.response.body=true
logbook.filter.enabled=true
logbook.format.json=true

# ?????? ?????
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n